/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

const CACHE_NAME = 'menteencalma-cache-v1';
const OFFLINE_URL = '/offline.html'; // Define an offline fallback page
const urlsToCache = [
  '/',
  '/index.html',
  OFFLINE_URL, // Add the offline page to cache
  '/icons/android-chrome-192x192.png',
  '/icons/android-chrome-512x512.png',
  '/icons/maskable_icon.png',
  '/icons/apple-touch-icon.png', // Add new icon
  '/icons/maskable_icon.svg', // Add new icon
  '/icons/shortcut-matrix.png', // Add shortcut icons
  '/icons/shortcut-dashboard.png', // Add shortcut icons
  // In a production build, dynamically inject paths to bundled JS/CSS assets here.
  // Example: '/assets/index-xxxxxxxx.js', '/assets/index-xxxxxxxx.css'
  // These paths are generated by Vite during the build process.
  // For development, the above are sufficient for basic offline functionality.
];

self.addEventListener('install', (event) => {
  console.log('Service Worker: Installing...');
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => {
        console.log('Service Worker: Caching app shell');
        return cache.addAll(urlsToCache);
      })
      .then(() => self.skipWaiting())
      .catch((error) => {
        console.error('Service Worker: Cache addAll failed', error);
      })
  );
});

self.addEventListener('activate', (event) => {
  console.log('Service Worker: Activating...');
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (cacheName !== CACHE_NAME) {
            console.log('Service Worker: Deleting old cache', cacheName);
            return caches.delete(cacheName);
          }
          return null;
        })
      );
    }).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  // Only handle GET requests
  if (event.request.method !== 'GET') {
    return;
  }

  event.respondWith(
    caches.match(event.request).then((response) => {
      // Cache hit - return response
      if (response) {
        console.log('Service Worker: Serving from cache:', event.request.url);
        return response;
      }

      // No cache hit - fetch from network
      console.log('Service Worker: Fetching from network:', event.request.url);
      return fetch(event.request).then((networkResponse) => {
        // Check if we received a valid response
        if (!networkResponse || networkResponse.status !== 200 || networkResponse.type !== 'basic') {
          return networkResponse;
        }

        // IMPORTANT: Clone the response. A response is a stream
        // and can only be consumed once. Since we are consuming this
        // once by the browser and once by the cache, we need to clone it.
        const responseToCache = networkResponse.clone();

        caches.open(CACHE_NAME).then((cache) => {
          cache.put(event.request, responseToCache);
        });

        return networkResponse;
      }).catch(() => {
        // If both network and cache fail, serve the offline page
        console.log('Service Worker: Network request failed, serving offline page.');
        return caches.match(OFFLINE_URL);
      });
    })
  );
});
